### ISSUE TITLE
Better respect  of original text and space    [Req ]

### ISSUE THREAD

**Issue by maurobotta** [raymondmars/chatgpt-chrome-translate-plugin#35]
Hi @raymondmars 

I have a request for a better respect  of original text and space    see this example:

![image](https://github.com/user-attachments/assets/f3ffdeb1-baa7-41ae-8406-f1a78e9fcf00)

Green -> Original text
Red    -> New (chtgpt..) Text translated

May you report better: blank lines BR , paragraph separation ,  bullet numbers, in the new translated text, allowing better reading ?

In short if I select a readable text, I would like to reread it after the translation in the same way.

Thanks for your project that I use every day :)

**Comment by raymondmars** [comment]
@maurobotta I have addressed this issue in the latest version 1.2.1. You can try it.

**Comment by maurobotta** [comment]
![image](https://github.com/user-attachments/assets/23eb993a-64a6-41bf-8035-49a1b94f2931)

There is a problem with mouse over, the text change color from White to black, no readable.

not in all sites... try this link https://www.reddit.com/r/StableDiffusion/comments/1ery98t/flux_nf4_v2_released/

**Comment by maurobotta** [comment]
with mouse outsite 
![image](https://github.com/user-attachments/assets/fa5ce3d3-388a-4a47-8939-d9c7fa56c52d)

**Comment by raymondmars** [comment]
@maurobotta will be fixed today.
