### ISSUE TITLE
X Special support - Twitter [Req]

### ISSUE THREAD

**Issue by maurobotta** [raymondmars/chatgpt-chrome-translate-plugin#39]
Hi @raymondmars , see image, is possible translate without MOUSE SELECTION  ?

For example in Twitter/x , i move mouse in a Twitter ( No selection text !! ) and press Q key for activate Your Plugin 

Translate ALL text of 1 twitter  ^_^

It could be a game changer for using your plugin :)

<img width="751" alt="image" src="https://github.com/user-attachments/assets/e306b0df-b951-4a65-984e-0dc4a694774e">

**Comment by raymondmars** [comment]
@maurobotta It is a nice idea, but it is a little conflicting with the current mode. Let me think about it and how to place this requirement. if you have any insights, welcome to comment here.

**Comment by maurobotta** [comment]
The Twitter speech is just one example; it's too limiting to translate a text (activate the plugin) AFTER selecting certain words. 

I would like to scroll through ... Reddit ... hover over/select the active part of the page, and with just one button... get the translation. The plugin would be much more useful than it is now.

**Comment by raymondmars** [comment]
@maurobotta I will add a new mode. Under this mode, you can translate text that your mouse hovered by a shortcut key. the mode is off by default. we can see the selecting text and the hovering text as two modes. You can only use one mode at a time.

**Comment by raymondmars** [comment]
@maurobotta The new features from 1.2.4 have implemented this requirement. You can wait for the update from Chrome.
